name: CI

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - uses: wireapp/github-action-wire-messenger@v1
        with:
          email: ${{secrets.WIRE_BOT_EMAIL}}
          password: ${{secrets.WIRE_BOT_PASSWORD}}
          conversation: '6936f0a3-be49-4f81-b4a7-d734661beff2'
          text: 'Building new packages...'
